server:
  port: 9090
  servlet:
    context-path: /api

spring:
  config:
    import: optional:file:.env[.properties],optional:file:env[.properties]
  datasource:
    url: jdbc:postgresql://192.168.1.35:5432/nt118_db
    username: nt118_user
    password: 'nt118_db'
    hikari:
      data-source-properties:
        TimeZone: UTC
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: ${SPRING_MAIL_HOST:}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  mail:
    from: ${APP_MAIL_FROM:no-reply@enggo.local}
  reset:
    otp-exp-min: ${APP_RESET_OTP_EXP_MIN:10}
